// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FBAccountKitUserData struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	AndroidId            string   `protobuf:"bytes,2,opt,name=androidId,proto3" json:"androidId,omitempty"`
	ImeiNumber           string   `protobuf:"bytes,3,opt,name=imeiNumber,proto3" json:"imeiNumber,omitempty"`
	Code                 string   `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FBAccountKitUserData) Reset()         { *m = FBAccountKitUserData{} }
func (m *FBAccountKitUserData) String() string { return proto.CompactTextString(m) }
func (*FBAccountKitUserData) ProtoMessage()    {}
func (*FBAccountKitUserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *FBAccountKitUserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FBAccountKitUserData.Unmarshal(m, b)
}
func (m *FBAccountKitUserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FBAccountKitUserData.Marshal(b, m, deterministic)
}
func (m *FBAccountKitUserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FBAccountKitUserData.Merge(m, src)
}
func (m *FBAccountKitUserData) XXX_Size() int {
	return xxx_messageInfo_FBAccountKitUserData.Size(m)
}
func (m *FBAccountKitUserData) XXX_DiscardUnknown() {
	xxx_messageInfo_FBAccountKitUserData.DiscardUnknown(m)
}

var xxx_messageInfo_FBAccountKitUserData proto.InternalMessageInfo

func (m *FBAccountKitUserData) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *FBAccountKitUserData) GetAndroidId() string {
	if m != nil {
		return m.AndroidId
	}
	return ""
}

func (m *FBAccountKitUserData) GetImeiNumber() string {
	if m != nil {
		return m.ImeiNumber
	}
	return ""
}

func (m *FBAccountKitUserData) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type RefreshTokenInput struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenInput) Reset()         { *m = RefreshTokenInput{} }
func (m *RefreshTokenInput) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenInput) ProtoMessage()    {}
func (*RefreshTokenInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *RefreshTokenInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenInput.Unmarshal(m, b)
}
func (m *RefreshTokenInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenInput.Marshal(b, m, deterministic)
}
func (m *RefreshTokenInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenInput.Merge(m, src)
}
func (m *RefreshTokenInput) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenInput.Size(m)
}
func (m *RefreshTokenInput) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenInput.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenInput proto.InternalMessageInfo

func (m *RefreshTokenInput) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RefreshTokenInput) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type RefreshTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenResponse) Reset()         { *m = RefreshTokenResponse{} }
func (m *RefreshTokenResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenResponse) ProtoMessage()    {}
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *RefreshTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenResponse.Unmarshal(m, b)
}
func (m *RefreshTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenResponse.Marshal(b, m, deterministic)
}
func (m *RefreshTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenResponse.Merge(m, src)
}
func (m *RefreshTokenResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenResponse.Size(m)
}
func (m *RefreshTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenResponse proto.InternalMessageInfo

func (m *RefreshTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserTokenResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	FirstTimeUser        string   `protobuf:"bytes,3,opt,name=firstTimeUser,proto3" json:"firstTimeUser,omitempty"`
	IsProfileComplete    string   `protobuf:"bytes,4,opt,name=isProfileComplete,proto3" json:"isProfileComplete,omitempty"`
	UserCreated          string   `protobuf:"bytes,5,opt,name=userCreated,proto3" json:"userCreated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserTokenResponse) Reset()         { *m = UserTokenResponse{} }
func (m *UserTokenResponse) String() string { return proto.CompactTextString(m) }
func (*UserTokenResponse) ProtoMessage()    {}
func (*UserTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *UserTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTokenResponse.Unmarshal(m, b)
}
func (m *UserTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTokenResponse.Marshal(b, m, deterministic)
}
func (m *UserTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTokenResponse.Merge(m, src)
}
func (m *UserTokenResponse) XXX_Size() int {
	return xxx_messageInfo_UserTokenResponse.Size(m)
}
func (m *UserTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserTokenResponse proto.InternalMessageInfo

func (m *UserTokenResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *UserTokenResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *UserTokenResponse) GetFirstTimeUser() string {
	if m != nil {
		return m.FirstTimeUser
	}
	return ""
}

func (m *UserTokenResponse) GetIsProfileComplete() string {
	if m != nil {
		return m.IsProfileComplete
	}
	return ""
}

func (m *UserTokenResponse) GetUserCreated() string {
	if m != nil {
		return m.UserCreated
	}
	return ""
}

func init() {
	proto.RegisterType((*FBAccountKitUserData)(nil), "auth.FBAccountKitUserData")
	proto.RegisterType((*RefreshTokenInput)(nil), "auth.RefreshTokenInput")
	proto.RegisterType((*RefreshTokenResponse)(nil), "auth.RefreshTokenResponse")
	proto.RegisterType((*UserTokenResponse)(nil), "auth.UserTokenResponse")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0x35, 0x15, 0x3a, 0xd6, 0x43, 0x86, 0x82, 0x21, 0x88, 0x94, 0xe0, 0xc1, 0x43, 0xe9,
	0x41, 0xcf, 0x1e, 0x6a, 0x55, 0xa8, 0x8a, 0x48, 0xa9, 0x3f, 0x60, 0x9b, 0x4c, 0xed, 0x62, 0xb3,
	0x1b, 0xf6, 0xe3, 0xea, 0xff, 0xf0, 0x57, 0xf9, 0x97, 0x24, 0xdb, 0x94, 0x6e, 0x48, 0xbd, 0x6d,
	0xde, 0x9b, 0x37, 0x6f, 0x66, 0x5e, 0x00, 0x98, 0x35, 0xeb, 0x71, 0xa9, 0xa4, 0x91, 0x18, 0x56,
	0xef, 0xf4, 0x1b, 0x06, 0x4f, 0xf7, 0x93, 0x2c, 0x93, 0x56, 0x98, 0x17, 0x6e, 0x3e, 0x34, 0xa9,
	0x07, 0x66, 0x18, 0x0e, 0xa0, 0x6b, 0xe4, 0x17, 0x89, 0x38, 0x18, 0x06, 0xd7, 0xbd, 0xf9, 0xf6,
	0x03, 0x2f, 0xa0, 0xc7, 0x44, 0xae, 0x24, 0xcf, 0x67, 0x79, 0xdc, 0x71, 0xcc, 0x1e, 0xc0, 0x4b,
	0x00, 0x5e, 0x10, 0x7f, 0xb3, 0xc5, 0x92, 0x54, 0x7c, 0xec, 0x68, 0x0f, 0x41, 0x84, 0x30, 0x93,
	0x39, 0xc5, 0xa1, 0x63, 0xdc, 0x3b, 0xbd, 0x83, 0x68, 0x4e, 0x2b, 0x45, 0x7a, 0xbd, 0xa8, 0x1c,
	0x66, 0xa2, 0xb4, 0xe6, 0x1f, 0xf3, 0x9d, 0xbc, 0xe3, 0xc9, 0x47, 0x30, 0xf0, 0xe5, 0x73, 0xd2,
	0xa5, 0x14, 0x9a, 0x0e, 0x77, 0x48, 0x7f, 0x03, 0x88, 0xaa, 0x0d, 0x9b, 0xb5, 0x43, 0x38, 0x65,
	0x59, 0x46, 0x5a, 0x2f, 0x3c, 0x85, 0x0f, 0x61, 0x0a, 0x7d, 0xe5, 0xb9, 0xd4, 0x13, 0x34, 0x30,
	0xbc, 0x82, 0xb3, 0x15, 0x57, 0xda, 0x2c, 0x78, 0x41, 0x95, 0x47, 0xbd, 0x7f, 0x13, 0xc4, 0x11,
	0x44, 0x5c, 0xbf, 0x2b, 0xb9, 0xe2, 0x1b, 0x9a, 0xca, 0xa2, 0xdc, 0x90, 0xd9, 0xdd, 0xa3, 0x4d,
	0x54, 0x93, 0x59, 0x4d, 0x6a, 0xaa, 0x88, 0x19, 0xca, 0xe3, 0xee, 0x76, 0x32, 0x0f, 0xba, 0xf9,
	0x09, 0x20, 0x9c, 0x58, 0xb3, 0xc6, 0x67, 0x88, 0xfc, 0x1c, 0x5f, 0xe5, 0x27, 0x17, 0x98, 0x8c,
	0x5d, 0xde, 0x87, 0x02, 0x4e, 0xce, 0xb7, 0x5c, 0xeb, 0x1c, 0xe9, 0x11, 0x3e, 0x42, 0xdf, 0x3f,
	0x2a, 0xd6, 0xa5, 0xad, 0x9c, 0x92, 0xa4, 0x4d, 0xec, 0xdb, 0x2c, 0x4f, 0xdc, 0x7f, 0x76, 0xfb,
	0x17, 0x00, 0x00, 0xff, 0xff, 0xfb, 0xd8, 0x45, 0x95, 0x75, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	FBAccountKitLogin(ctx context.Context, in *FBAccountKitUserData, opts ...grpc.CallOption) (*UserTokenResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenInput, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) FBAccountKitLogin(ctx context.Context, in *FBAccountKitUserData, opts ...grpc.CallOption) (*UserTokenResponse, error) {
	out := new(UserTokenResponse)
	err := c.cc.Invoke(ctx, "/auth.Auth/FBAccountKitLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) RefreshToken(ctx context.Context, in *RefreshTokenInput, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, "/auth.Auth/RefreshToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	FBAccountKitLogin(context.Context, *FBAccountKitUserData) (*UserTokenResponse, error)
	RefreshToken(context.Context, *RefreshTokenInput) (*RefreshTokenResponse, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_FBAccountKitLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FBAccountKitUserData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).FBAccountKitLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/FBAccountKitLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).FBAccountKitLogin(ctx, req.(*FBAccountKitUserData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/RefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).RefreshToken(ctx, req.(*RefreshTokenInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FBAccountKitLogin",
			Handler:    _Auth_FBAccountKitLogin_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _Auth_RefreshToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
