// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FBAccountKitUserData struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	AndroidId            string   `protobuf:"bytes,2,opt,name=androidId,proto3" json:"androidId,omitempty"`
	ImeiNumber           string   `protobuf:"bytes,3,opt,name=imeiNumber,proto3" json:"imeiNumber,omitempty"`
	Code                 string   `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FBAccountKitUserData) Reset()         { *m = FBAccountKitUserData{} }
func (m *FBAccountKitUserData) String() string { return proto.CompactTextString(m) }
func (*FBAccountKitUserData) ProtoMessage()    {}
func (*FBAccountKitUserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *FBAccountKitUserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FBAccountKitUserData.Unmarshal(m, b)
}
func (m *FBAccountKitUserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FBAccountKitUserData.Marshal(b, m, deterministic)
}
func (m *FBAccountKitUserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FBAccountKitUserData.Merge(m, src)
}
func (m *FBAccountKitUserData) XXX_Size() int {
	return xxx_messageInfo_FBAccountKitUserData.Size(m)
}
func (m *FBAccountKitUserData) XXX_DiscardUnknown() {
	xxx_messageInfo_FBAccountKitUserData.DiscardUnknown(m)
}

var xxx_messageInfo_FBAccountKitUserData proto.InternalMessageInfo

func (m *FBAccountKitUserData) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *FBAccountKitUserData) GetAndroidId() string {
	if m != nil {
		return m.AndroidId
	}
	return ""
}

func (m *FBAccountKitUserData) GetImeiNumber() string {
	if m != nil {
		return m.ImeiNumber
	}
	return ""
}

func (m *FBAccountKitUserData) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type RefreshTokenInput struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenInput) Reset()         { *m = RefreshTokenInput{} }
func (m *RefreshTokenInput) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenInput) ProtoMessage()    {}
func (*RefreshTokenInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *RefreshTokenInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenInput.Unmarshal(m, b)
}
func (m *RefreshTokenInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenInput.Marshal(b, m, deterministic)
}
func (m *RefreshTokenInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenInput.Merge(m, src)
}
func (m *RefreshTokenInput) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenInput.Size(m)
}
func (m *RefreshTokenInput) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenInput.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenInput proto.InternalMessageInfo

func (m *RefreshTokenInput) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RefreshTokenInput) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type RefreshTokenResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenResponse) Reset()         { *m = RefreshTokenResponse{} }
func (m *RefreshTokenResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenResponse) ProtoMessage()    {}
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *RefreshTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenResponse.Unmarshal(m, b)
}
func (m *RefreshTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenResponse.Marshal(b, m, deterministic)
}
func (m *RefreshTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenResponse.Merge(m, src)
}
func (m *RefreshTokenResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenResponse.Size(m)
}
func (m *RefreshTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenResponse proto.InternalMessageInfo

func (m *RefreshTokenResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type UserTokenResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	FirstTimeUser        string   `protobuf:"bytes,3,opt,name=firstTimeUser,proto3" json:"firstTimeUser,omitempty"`
	IsProfileComplete    string   `protobuf:"bytes,4,opt,name=isProfileComplete,proto3" json:"isProfileComplete,omitempty"`
	UserCreated          string   `protobuf:"bytes,5,opt,name=userCreated,proto3" json:"userCreated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserTokenResponse) Reset()         { *m = UserTokenResponse{} }
func (m *UserTokenResponse) String() string { return proto.CompactTextString(m) }
func (*UserTokenResponse) ProtoMessage()    {}
func (*UserTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *UserTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserTokenResponse.Unmarshal(m, b)
}
func (m *UserTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserTokenResponse.Marshal(b, m, deterministic)
}
func (m *UserTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserTokenResponse.Merge(m, src)
}
func (m *UserTokenResponse) XXX_Size() int {
	return xxx_messageInfo_UserTokenResponse.Size(m)
}
func (m *UserTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserTokenResponse proto.InternalMessageInfo

func (m *UserTokenResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *UserTokenResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *UserTokenResponse) GetFirstTimeUser() string {
	if m != nil {
		return m.FirstTimeUser
	}
	return ""
}

func (m *UserTokenResponse) GetIsProfileComplete() string {
	if m != nil {
		return m.IsProfileComplete
	}
	return ""
}

func (m *UserTokenResponse) GetUserCreated() string {
	if m != nil {
		return m.UserCreated
	}
	return ""
}

type SendOTPInput struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	AndroidId            string   `protobuf:"bytes,2,opt,name=androidId,proto3" json:"androidId,omitempty"`
	Resend               bool     `protobuf:"varint,3,opt,name=resend,proto3" json:"resend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendOTPInput) Reset()         { *m = SendOTPInput{} }
func (m *SendOTPInput) String() string { return proto.CompactTextString(m) }
func (*SendOTPInput) ProtoMessage()    {}
func (*SendOTPInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *SendOTPInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendOTPInput.Unmarshal(m, b)
}
func (m *SendOTPInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendOTPInput.Marshal(b, m, deterministic)
}
func (m *SendOTPInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendOTPInput.Merge(m, src)
}
func (m *SendOTPInput) XXX_Size() int {
	return xxx_messageInfo_SendOTPInput.Size(m)
}
func (m *SendOTPInput) XXX_DiscardUnknown() {
	xxx_messageInfo_SendOTPInput.DiscardUnknown(m)
}

var xxx_messageInfo_SendOTPInput proto.InternalMessageInfo

func (m *SendOTPInput) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SendOTPInput) GetAndroidId() string {
	if m != nil {
		return m.AndroidId
	}
	return ""
}

func (m *SendOTPInput) GetResend() bool {
	if m != nil {
		return m.Resend
	}
	return false
}

type SendOTPResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendOTPResponse) Reset()         { *m = SendOTPResponse{} }
func (m *SendOTPResponse) String() string { return proto.CompactTextString(m) }
func (*SendOTPResponse) ProtoMessage()    {}
func (*SendOTPResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *SendOTPResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendOTPResponse.Unmarshal(m, b)
}
func (m *SendOTPResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendOTPResponse.Marshal(b, m, deterministic)
}
func (m *SendOTPResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendOTPResponse.Merge(m, src)
}
func (m *SendOTPResponse) XXX_Size() int {
	return xxx_messageInfo_SendOTPResponse.Size(m)
}
func (m *SendOTPResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendOTPResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendOTPResponse proto.InternalMessageInfo

func (m *SendOTPResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type VerifyOTPInput struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Otp                  string   `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
	AndroidId            string   `protobuf:"bytes,3,opt,name=androidId,proto3" json:"androidId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyOTPInput) Reset()         { *m = VerifyOTPInput{} }
func (m *VerifyOTPInput) String() string { return proto.CompactTextString(m) }
func (*VerifyOTPInput) ProtoMessage()    {}
func (*VerifyOTPInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{6}
}

func (m *VerifyOTPInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyOTPInput.Unmarshal(m, b)
}
func (m *VerifyOTPInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyOTPInput.Marshal(b, m, deterministic)
}
func (m *VerifyOTPInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyOTPInput.Merge(m, src)
}
func (m *VerifyOTPInput) XXX_Size() int {
	return xxx_messageInfo_VerifyOTPInput.Size(m)
}
func (m *VerifyOTPInput) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyOTPInput.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyOTPInput proto.InternalMessageInfo

func (m *VerifyOTPInput) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *VerifyOTPInput) GetOtp() string {
	if m != nil {
		return m.Otp
	}
	return ""
}

func (m *VerifyOTPInput) GetAndroidId() string {
	if m != nil {
		return m.AndroidId
	}
	return ""
}

type VerifyOTPResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyOTPResponse) Reset()         { *m = VerifyOTPResponse{} }
func (m *VerifyOTPResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyOTPResponse) ProtoMessage()    {}
func (*VerifyOTPResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{7}
}

func (m *VerifyOTPResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyOTPResponse.Unmarshal(m, b)
}
func (m *VerifyOTPResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyOTPResponse.Marshal(b, m, deterministic)
}
func (m *VerifyOTPResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyOTPResponse.Merge(m, src)
}
func (m *VerifyOTPResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyOTPResponse.Size(m)
}
func (m *VerifyOTPResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyOTPResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyOTPResponse proto.InternalMessageInfo

func (m *VerifyOTPResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*FBAccountKitUserData)(nil), "auth.FBAccountKitUserData")
	proto.RegisterType((*RefreshTokenInput)(nil), "auth.RefreshTokenInput")
	proto.RegisterType((*RefreshTokenResponse)(nil), "auth.RefreshTokenResponse")
	proto.RegisterType((*UserTokenResponse)(nil), "auth.UserTokenResponse")
	proto.RegisterType((*SendOTPInput)(nil), "auth.SendOTPInput")
	proto.RegisterType((*SendOTPResponse)(nil), "auth.SendOTPResponse")
	proto.RegisterType((*VerifyOTPInput)(nil), "auth.VerifyOTPInput")
	proto.RegisterType((*VerifyOTPResponse)(nil), "auth.VerifyOTPResponse")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0xee, 0xfe, 0x74, 0x61, 0x87, 0xe5, 0x27, 0xa3, 0xa5, 0x44, 0x11, 0x42, 0x95, 0xc5, 0x81,
	0x4a, 0x55, 0x0f, 0x20, 0x71, 0x82, 0x43, 0x29, 0x20, 0x15, 0x10, 0x54, 0x4b, 0xe8, 0x81, 0x5b,
	0x9a, 0x4c, 0x88, 0x45, 0x63, 0x47, 0xb6, 0x73, 0xe0, 0xc2, 0x2b, 0xf0, 0x68, 0xbc, 0x12, 0x8a,
	0xe3, 0x04, 0x87, 0x94, 0xee, 0xcd, 0xf3, 0xcd, 0xdf, 0x37, 0x33, 0x9f, 0x01, 0x92, 0xda, 0x14,
	0x47, 0x95, 0x92, 0x46, 0xe2, 0xbc, 0x79, 0xb3, 0x9f, 0xb0, 0x7e, 0xfb, 0xea, 0x38, 0x4d, 0x65,
	0x2d, 0xcc, 0x7b, 0x6e, 0xbe, 0x68, 0x52, 0xaf, 0x13, 0x93, 0xe0, 0x1a, 0x76, 0x8d, 0xfc, 0x4e,
	0x22, 0x9c, 0xec, 0x4f, 0x9e, 0x2c, 0x37, 0xad, 0x81, 0x0f, 0x61, 0x99, 0x88, 0x4c, 0x49, 0x9e,
	0x9d, 0x66, 0xe1, 0xd4, 0x7a, 0xfe, 0x02, 0xf8, 0x08, 0x80, 0x97, 0xc4, 0x3f, 0xd6, 0xe5, 0x05,
	0xa9, 0x70, 0x66, 0xdd, 0x1e, 0x82, 0x08, 0xf3, 0x54, 0x66, 0x14, 0xce, 0xad, 0xc7, 0xbe, 0xd9,
	0x4b, 0x08, 0x36, 0x94, 0x2b, 0xd2, 0x45, 0xdc, 0x74, 0x38, 0x15, 0x55, 0x6d, 0xfe, 0xd3, 0xbc,
	0x4b, 0x9f, 0x7a, 0xe9, 0x87, 0xb0, 0xf6, 0xd3, 0x37, 0xa4, 0x2b, 0x29, 0x34, 0x5d, 0x5d, 0x81,
	0xfd, 0x9e, 0x40, 0xd0, 0x4c, 0x38, 0x8c, 0xdd, 0x87, 0x5b, 0x49, 0x9a, 0x92, 0xd6, 0xb1, 0x97,
	0xe1, 0x43, 0xc8, 0x60, 0xa5, 0xbc, 0x2e, 0x8e, 0xc1, 0x00, 0xc3, 0xc7, 0x70, 0x3b, 0xe7, 0x4a,
	0x9b, 0x98, 0x97, 0xd4, 0xf4, 0x70, 0xf3, 0x0f, 0x41, 0x3c, 0x84, 0x80, 0xeb, 0x33, 0x25, 0x73,
	0x7e, 0x49, 0x27, 0xb2, 0xac, 0x2e, 0xc9, 0x74, 0xfb, 0x18, 0x3b, 0x1a, 0x66, 0xb5, 0x26, 0x75,
	0xa2, 0x28, 0x31, 0x94, 0x85, 0xbb, 0x2d, 0x33, 0x0f, 0x62, 0x5f, 0x61, 0xf5, 0x99, 0x44, 0xf6,
	0x29, 0x3e, 0xeb, 0x37, 0x57, 0x15, 0x52, 0x50, 0x37, 0xb7, 0x35, 0xb6, 0x9c, 0x6d, 0x0f, 0x16,
	0x8a, 0x34, 0x89, 0xcc, 0x52, 0xbe, 0xb9, 0x71, 0x16, 0x3b, 0x80, 0xbb, 0xae, 0x76, 0xbf, 0xaa,
	0x3d, 0x58, 0x68, 0x93, 0x98, 0x5a, 0xbb, 0xfa, 0xce, 0x62, 0xe7, 0x70, 0xe7, 0x9c, 0x14, 0xcf,
	0x7f, 0x6c, 0x21, 0x72, 0x0f, 0x66, 0xd2, 0x54, 0x8e, 0x42, 0xf3, 0x1c, 0x52, 0x9b, 0xfd, 0x43,
	0x8d, 0x1d, 0x40, 0xd0, 0xd7, 0xbd, 0xfe, 0xb6, 0x4f, 0x7f, 0x4d, 0x61, 0x7e, 0x5c, 0x9b, 0x02,
	0xdf, 0x41, 0xe0, 0x2b, 0xfa, 0x83, 0xfc, 0xc6, 0x05, 0x46, 0x47, 0x56, 0xf9, 0x57, 0x49, 0x3d,
	0x7a, 0xd0, 0xfa, 0x46, 0xc2, 0x60, 0x3b, 0xf8, 0x06, 0x56, 0xbe, 0xbc, 0xd0, 0x85, 0x8e, 0x14,
	0x1b, 0x45, 0x63, 0x87, 0x57, 0xe6, 0x39, 0xdc, 0x70, 0x9b, 0x44, 0x6c, 0x03, 0xfd, 0xa3, 0x45,
	0xf7, 0x07, 0x98, 0x97, 0xf7, 0x02, 0x96, 0xfd, 0xf8, 0xb8, 0x6e, 0xa3, 0x86, 0x7b, 0xee, 0xc8,
	0x8f, 0xb6, 0xc4, 0x76, 0x2e, 0x16, 0xf6, 0x9f, 0x3f, 0xfb, 0x13, 0x00, 0x00, 0xff, 0xff, 0x5c,
	0x23, 0x7d, 0x2e, 0xf5, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthClient is the client API for Auth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthClient interface {
	FBAccountKitLogin(ctx context.Context, in *FBAccountKitUserData, opts ...grpc.CallOption) (*UserTokenResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenInput, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	SendOTP(ctx context.Context, in *SendOTPInput, opts ...grpc.CallOption) (*SendOTPResponse, error)
	VerifyOTP(ctx context.Context, in *VerifyOTPInput, opts ...grpc.CallOption) (*VerifyOTPResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) FBAccountKitLogin(ctx context.Context, in *FBAccountKitUserData, opts ...grpc.CallOption) (*UserTokenResponse, error) {
	out := new(UserTokenResponse)
	err := c.cc.Invoke(ctx, "/auth.Auth/FBAccountKitLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) RefreshToken(ctx context.Context, in *RefreshTokenInput, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, "/auth.Auth/RefreshToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) SendOTP(ctx context.Context, in *SendOTPInput, opts ...grpc.CallOption) (*SendOTPResponse, error) {
	out := new(SendOTPResponse)
	err := c.cc.Invoke(ctx, "/auth.Auth/SendOTP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) VerifyOTP(ctx context.Context, in *VerifyOTPInput, opts ...grpc.CallOption) (*VerifyOTPResponse, error) {
	out := new(VerifyOTPResponse)
	err := c.cc.Invoke(ctx, "/auth.Auth/VerifyOTP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServer is the server API for Auth service.
type AuthServer interface {
	FBAccountKitLogin(context.Context, *FBAccountKitUserData) (*UserTokenResponse, error)
	RefreshToken(context.Context, *RefreshTokenInput) (*RefreshTokenResponse, error)
	SendOTP(context.Context, *SendOTPInput) (*SendOTPResponse, error)
	VerifyOTP(context.Context, *VerifyOTPInput) (*VerifyOTPResponse, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_FBAccountKitLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FBAccountKitUserData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).FBAccountKitLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/FBAccountKitLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).FBAccountKitLogin(ctx, req.(*FBAccountKitUserData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/RefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).RefreshToken(ctx, req.(*RefreshTokenInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_SendOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendOTPInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).SendOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/SendOTP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).SendOTP(ctx, req.(*SendOTPInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_VerifyOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyOTPInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).VerifyOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/VerifyOTP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).VerifyOTP(ctx, req.(*VerifyOTPInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FBAccountKitLogin",
			Handler:    _Auth_FBAccountKitLogin_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _Auth_RefreshToken_Handler,
		},
		{
			MethodName: "SendOTP",
			Handler:    _Auth_SendOTP_Handler,
		},
		{
			MethodName: "VerifyOTP",
			Handler:    _Auth_VerifyOTP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
